theme: minima
title: Abderrahman Ait-Ali
description: Transport Economics & Railway Systems Research
author: Abderrahman Ait-Ali
social:
  github: abdeaitali
  linkedin: abdeaitali
  scholar: 3t1aBqYAAAAJ
header_pages:
  - publications.md
  - projects.md
  - teaching.md
  - talks.md
  - contact.md
